use std::{collections::HashMap, fmt::Display};

use aho_corasick::AhoCorasick;
use regex::Match;

use crate::{chat::ChatMessage, prelude::InferIter};

pub const SCHEMA_PASSTHROUGH_INPUT: &str = "input";

/// Helper function for parsing context keys in the format "{key}" and substituting
/// them with their JSON values from the context.
fn substitute_context_keys(input: &str, context: &HashMap<String, String>) -> String {
    // Build the patterns and replacements for the Aho-Corasick algorithm
    let (patterns, replacements): (Vec<String>, Vec<String>) = context
        .iter()
        .flat_map(|(k, v)| {
            [
                (format!("{{{}}}", k), v.clone()),
                (format!("{{ {} }}", k), v.clone()),
            ]
        })
        .unzip();

    // Instead of a simple replace we use aho-corasick to find and replace all context keys in one pass
    let ac = AhoCorasick::new(patterns).unwrap();
    ac.replace_all(input, &replacements)
}

/// Helper function for finding context keys in the format "{key}" and returning them as a vector of strings.
fn find_context_keys<'a>(input: &'a str) -> Vec<Match<'a>> {
    // Use a regex to find all context keys in the input string
    let re = regex::Regex::new(r"\{([^}]*)\}").unwrap();
    re.captures_iter(input)
        .filter_map(|cap| cap.get(1))
        .collect()
}

/// Helper function for creating example user messages and responses based on the input and output schemas, which can be used to provide examples to the model.
pub fn create_chat_wrapper_examples(
    input_schema: &ChatSchema,
    output_schema: &ChatSchema,
    input_output_pairs: impl IntoIterator<Item = (HashMap<String, String>, HashMap<String, String>)>,
) -> Vec<ChatMessage> {
    input_output_pairs
        .into_iter()
        .flat_map(move |(input_context, output_values)| {
            let input_string = input_schema.to_input_string(&input_context);
            let output_string = output_schema.to_output_string(output_values);
            [
                ChatMessage::user(input_string),
                ChatMessage::assistant(output_string),
            ]
        })
        .collect()
}

/// The output from writing an output schema as returned by `ChatSchema::write_output`, which includes the inferred output string as well as any captures.
#[derive(Debug, Clone)]
pub struct SchemaWriteOutput {
    full_string: String,
    captures: HashMap<String, String>,
}

impl SchemaWriteOutput {
    /// Gets the captures from the output, which are inferred values that were captured during the writing of the output schema.
    pub fn captures(&self) -> &HashMap<String, String> {
        &self.captures
    }

    /// Gets the full output string as generated by the schema.
    pub fn full_string(&self) -> &str {
        &self.full_string
    }

    /// Gets a specific capture by key, if it exists.
    pub fn get_capture(&self, key: &str) -> Option<&String> {
        self.captures.get(key)
    }

    /// Takes ownership of the captures and full string, returning them as a tuple.
    pub fn into_parts(self) -> (HashMap<String, String>, String) {
        (self.captures, self.full_string)
    }

    /// Takes ownership of the captures, returning them as a HashMap.
    pub fn into_captures(self) -> HashMap<String, String> {
        self.captures
    }

    /// Takes ownership of the full string, returning it as a String.
    pub fn into_full_string(self) -> String {
        self.full_string
    }
}

impl AsRef<str> for SchemaWriteOutput {
    fn as_ref(&self) -> &str {
        &self.full_string
    }
}

/// A schema defining the input or output for a chat-based model.
/// Schemas are made up of `SchemaBlock`s, which are individual components of the schema that define specific parts
/// of the input or output. Each block contributes to the model input or output in a specific way,
/// and the combination of blocks defines the overall structure and content of the input or output.
/// Context keys in the format {key} can usually be used in the text of a block to reference values from the context,
/// which is passed to the input schema. For the output schema the keys are instead replaced by inference using the key contents as an end sequence.
/// If an output key ends with a "=>" and then a key identifier, then the inferred value will be captured and returned in the output with said key.
pub struct ChatSchema {
    blocks: Vec<Box<dyn SchemaBlock>>,
}

impl ChatSchema {
    /// Creates a new empty schema.
    pub fn new() -> Self {
        Self { blocks: Vec::new() }
    }

    /// Creates a new schema from a vector of blocks.
    pub fn from_blocks(blocks: Vec<Box<dyn SchemaBlock>>) -> Self {
        Self { blocks }
    }

    /// Creates a passthrough input schema which simply represents the input string.
    pub fn passthrough_input() -> Self {
        Self::new().with_text(None, format!("{{{}}}", SCHEMA_PASSTHROUGH_INPUT))
    }

    /// Creates a passthrough output schema which simply represents the output string.
    pub fn passthrough_output() -> Self {
        Self::new().with_text(None, "{}")
    }

    /// Gets the blocks that make up the schema.
    pub fn blocks(&self) -> &[Box<dyn SchemaBlock>] {
        &self.blocks
    }

    /// Adds a block to the schema.
    pub fn add_block(&mut self, block: Box<dyn SchemaBlock>) {
        self.blocks.push(block);
    }

    /// Add a text block to the schema with the given label and text.
    /// Also returns self to allow for chaining.
    pub fn with_text(mut self, label: Option<String>, text: impl Display) -> Self {
        self.add_block(Box::new(TextBlock::new(label, text)));
        self
    }

    /// Writes the schema to an InferIter as an input, using the given context map to substitute any context keys in the blocks.
    /// Also returns the final input string as written to the InferIter.
    pub fn write_input(&self, iter: &mut InferIter, context: &HashMap<String, String>) -> String {
        let mut written_so_far = String::new();
        for (i, block) in self.blocks.iter().enumerate() {
            // Write each block to the InferIter with context substitution, and add a newline after each block (except the last one)
            written_so_far.push_str(&block.write_input(iter, context));
            if i < self.blocks.len() - 1 {
                iter.push_str("\n\n");
                written_so_far.push_str("\n\n");
            }
        }

        written_so_far
    }

    /// Writes the schema to an InferIter as an output.
    pub fn write_output(&self, iter: &mut InferIter) -> SchemaWriteOutput {
        let mut written_so_far = String::new();
        let mut captures = HashMap::new();
        for (i, block) in self.blocks.iter().enumerate() {
            // Write each block to the InferIter, and add a newline after each block (except the last one)
            written_so_far.push_str(&block.write_output(iter, &mut captures));
            if i < self.blocks.len() - 1 {
                iter.push_str("\n\n");
                written_so_far.push_str("\n\n");
            }
        }

        SchemaWriteOutput {
            full_string: written_so_far,
            captures,
        }
    }

    /// Converts the schema to a string as an input, using the given context map to substitute any context keys in the blocks.
    pub fn to_input_string(&self, context: &HashMap<String, String>) -> String {
        self.blocks
            .iter()
            .map(|block| block.to_input_string(context))
            .collect::<Vec<_>>()
            .join("\n\n")
    }

    /// Converts the schema to a string as an output, replacing each inferable key with the corresponding value in `output_captures`.
    pub fn to_output_string(&self, output_captures: HashMap<String, String>) -> String {
        let mut written_so_far = String::new();
        for (i, block) in self.blocks.iter().enumerate() {
            // For each block, replace any inferable keys with the next value from the outputs iterator
            let block_string = block.to_raw_string();
            let keys = find_context_keys(&block_string);
            if keys.is_empty() {
                written_so_far.push_str(&block_string);
            } else {
                let mut last_index = 0;
                for key in keys {
                    // If the key contains a capture identifier (indicated by "=>"), split the key and use the part after "=>" as the capture key
                    // The part before "=>" is used as the end sequence later
                    let key_str = key.as_str();
                    let (end_sequences_str, capture_key) = if let Some(split_index) =
                        key_str.find("=>")
                    {
                        (
                            key_str[..split_index].trim(),
                            key_str[split_index + 2..].trim(),
                        )
                    } else {
                        panic!(
                            "Output schema keys must be in the format in the format {{end|sequences|here => capture_key_here}} to capture inferred values, but key '{}' does not contain '=>'",
                            key_str
                        );
                    };

                    let start = key.start() - 1; // Include the opening '{'
                    let end = key.end() + 1; // Include the closing '}'

                    // Push the string before the key
                    if start > last_index {
                        written_so_far.push_str(&block_string[last_index..start]);
                    }

                    // Get all end sequences from the key (may be multiple separated by '|')
                    let end_sequences = end_sequences_str
                        .split('|')
                        .filter_map(|s| {
                            let trimmed = s.trim();
                            if trimmed.is_empty() {
                                None
                            } else {
                                Some(trimmed)
                            }
                        })
                        .collect::<Vec<_>>();

                    // Get the output value for the key from the output captures
                    let output_value = output_captures.get(capture_key).unwrap_or_else(|| panic!("Output captures must contain a value for key '{}', but it was not found in the provided output captures: {:?}", capture_key, output_captures)).trim();
                    written_so_far.push_str(output_value);

                    // If there are end sequences, and the output value does not end with one of them, push the first end sequence onto the output value
                    if !end_sequences.is_empty()
                        && !end_sequences.iter().any(|&seq| output_value.ends_with(seq))
                    {
                        written_so_far.push_str(end_sequences[0]);
                    }

                    last_index = end;
                }

                // Push any remaining string after the last key
                if last_index < block_string.len() {
                    written_so_far.push_str(&block_string[last_index..]);
                }
            }

            // Add a newline after each block (except the last one)
            if i < self.blocks.len() - 1 {
                written_so_far.push_str("\n\n");
            }
        }

        written_so_far
    }
}

impl Default for ChatSchema {
    fn default() -> Self {
        Self::new()
    }
}

impl Clone for ChatSchema {
    fn clone(&self) -> Self {
        Self {
            blocks: self.blocks.iter().map(|b| b.clone_box()).collect(),
        }
    }
}

impl From<&str> for ChatSchema {
    fn from(s: &str) -> Self {
        ChatSchema::new().with_text(None, s)
    }
}

/// A trait representing a block of the schema. This can be implemented by different types of blocks to define their behavior and content.
pub trait SchemaBlock {
    /// Clones the block. This is needed because the schema contains trait objects which are not clonable by default.
    fn clone_box(&self) -> Box<dyn SchemaBlock>;

    /// The optional label of the block, which acts as a heading or identifier for the block in the schema.
    fn label(&self) -> Option<&str> {
        None
    }

    /// Converts the block to a raw string for input or output without substituting context keys.
    fn to_raw_string(&self) -> String;

    /// Writes the block to an InferIter as an input after substituting context map keys, using the given context map.
    fn write_input(&self, iter: &mut InferIter, context: &HashMap<String, String>) -> String {
        let raw = self.to_raw_string();
        let substituted = substitute_context_keys(&raw, context);
        iter.push_str(&substituted);
        substituted
    }

    // Converts the block to an input string after substituting context map keys, using the given context map.
    fn to_input_string(&self, context: &HashMap<String, String>) -> String {
        substitute_context_keys(&self.to_raw_string(), context)
    }

    /// Writes the block to an InferIter, using the given context map.
    fn write_output(&self, iter: &mut InferIter, captures: &mut HashMap<String, String>) -> String {
        let mut written_so_far = String::new();
        let raw = self.to_raw_string();

        // Find all keys in the raw string and use them as end sequences for inference, then replace them with the inferred values
        let keys = find_context_keys(&raw);

        // If there are no keys we can just push the raw string to the output
        if keys.is_empty() {
            written_so_far.push_str(&raw);
            iter.push_str(&raw);
            return written_so_far;
        }

        // Otherwise write the string up to the each key, then infer until the matching end sequence is found, and repeat until no keys remain.
        let mut last_index = 0;
        for key in keys {
            // If the key contains a capture identifier (indicated by "=>"), split the key and use the part after "=>" as the capture key
            // The part before "=>" is used as the end sequence for inference as normal
            let key_str = key.as_str();
            let (end_sequences_str, capture_key) = if let Some(split_index) = key_str.find("=>") {
                (
                    key_str[..split_index].trim(),
                    key_str[split_index + 2..].trim(),
                )
            } else {
                panic!(
                    "Output schema keys must be in the format in the format {{end|sequences|here => capture_key_here}} to capture inferred values, but key '{}' does not contain '=>'",
                    key_str
                );
            };

            let start = key.start() - 1; // Include the opening '{'
            let end = key.end() + 1; // Include the closing '}'

            // Push the string before the key
            if start > last_index {
                written_so_far.push_str(&raw[last_index..start]);
                iter.push_str(&raw[last_index..start]);
            }

            // Get the end sequence(s) from the key (may be multiple separated by '|')
            let end_sequences: Vec<&str> = end_sequences_str
                .split('|')
                .filter_map(|s| {
                    let trimmed = s.trim();
                    if trimmed.is_empty() {
                        None
                    } else {
                        Some(trimmed)
                    }
                })
                .collect();

            // Infer until the end sequence is found, this will end up in the InferIter anyway so no need to push
            let inferred = iter.complete(&end_sequences);
            // Save the inferred value in the captures map with the capture key
            captures.insert(capture_key.to_string(), inferred.result().to_string());
            // Push the end sequence onto the inferred string because it is not normally included
            let end_sequence = inferred.end_sequence().unwrap_or_default().to_string();
            let mut inferred = inferred.unwrap();
            inferred.push_str(&end_sequence);
            // Also update the output string with the inferred value
            written_so_far.push_str(&inferred);

            // Update the last index to the end of the key
            last_index = end;
        }

        written_so_far
    }
}

/// Simply represents a block of text in the schema, which can be used to provide instructions, context, or other information to the model.
#[derive(Clone)]
pub struct TextBlock {
    label: Option<String>,
    text: String,
}

impl TextBlock {
    pub fn new(label: Option<String>, text: impl Display) -> Self {
        Self {
            label,
            text: text.to_string(),
        }
    }
}

impl SchemaBlock for TextBlock {
    fn clone_box(&self) -> Box<dyn SchemaBlock> {
        Box::new(self.clone())
    }

    fn label(&self) -> Option<&str> {
        self.label.as_deref()
    }

    fn to_raw_string(&self) -> String {
        let label_part = if let Some(label) = &self.label {
            format!("**{}:**\n", label)
        } else {
            String::new()
        };
        format!("{}{}", label_part, self.text)
    }
}
