use std::fmt::Display;

use crate::prelude::*;

/// A single parsed instruction generated by an `Instructor`.
#[derive(Debug)]
pub struct ParsedInstruction<'a> {
    pub name: &'a str,
    pub args: JsonMap,
}

/// A single instruction definition which `Instructor` can use to parse instructions from text.
#[derive(Debug)]
pub struct InstructionDefinition {
    name: String,
    param_names: Vec<String>,
    example_instruction: String,
    example_args: Vec<JsonValue>,
}

impl InstructionDefinition {
    /// Creates a new instruction definition with the provided example instruction, example arguments, name, and argument names.
    pub fn new(
        name: impl Display,
        param_names: Vec<String>,
        example_instruction: impl Display,
        example_args: Vec<JsonValue>,
    ) -> InstructionDefinition {
        InstructionDefinition {
            name: name.to_string(),
            param_names,
            example_instruction: example_instruction.to_string(),
            example_args,
        }
    }
}

/// Takes string instructions and then parses them to retrieve the relevant information
pub struct Instructor {
    chat: Chat,
    instruction_definitions: Vec<InstructionDefinition>,
}

impl Instructor {
    // A system prompt which instructs the model to take in text instructions and output function calls which represent the instructions.
    const SYSTEM_PROMPT: &str = "You are an assistant that takes a text description of an action/instruction, \
            and writes a function call which represents said action/instruction. You may call only the functions \
            defined below.";
    /// We use function definitions to parse instructions using the model.
    /// To make the model more deterministic in its returning of function names we use a prefix for all function names.
    const FUNC_PREFIX: &str = "fn_action_";
    /// Attempts to parse instructions from text until we just pass None back to signify that we failed to parse an instruction.
    const MAX_PARSE_ATTEMPTS: usize = 8;

    /// Creates a new Instructor with the provided model, seed, temperature, and instruction definitions.
    pub fn new(model: &mut Model, instruction_definitions: Vec<InstructionDefinition>) -> Self {
        // Create examples as chat history
        let example_chat_history = instruction_definitions.iter().flat_map(|def| {
            let user_message = ChatMessage::new(ChatRole::User, format!("Please give me a function call for the following instruction text:\n\"{}\"", def.example_instruction));
            let response_message = ChatMessage::new(ChatRole::Assistant, format!(
                "Here is the function call which matches the instruction:\n```typescript\n{}{}({})```",
                Self::FUNC_PREFIX,
                def.name,
                // Write out the parameter names before the arguments to said parameters in the function call for clarity
                def.param_names.iter().zip(def.example_args.iter())
                    .map(|(name, arg)| format!("{}: {}", name, arg))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));

            [user_message, response_message]
        }).collect::<Vec<_>>();

        // Make a string of the instruction definitions in a typescript function signature format inside a code block.
        // This will be put in extra data.
        // Argument types are decided by the example JSON values provided in the instruction definitions
        let mut instruction_definitions_str = "```typescript\n".to_string();
        for def in &instruction_definitions {
            // Get the argument types from the example JSON values
            // These should be typescript type names
            let arg_types = def
                .example_args
                .iter()
                .map(|arg| {
                    if arg.is_string() {
                        "string".to_string()
                    } else if arg.is_number() {
                        "number".to_string()
                    } else if arg.is_boolean() {
                        "boolean".to_string()
                    } else if arg.is_array() {
                        "array".to_string()
                    } else {
                        "object".to_string()
                    }
                })
                .collect::<Vec<_>>();

            // Format the instruction definition as a typescript function signature and add it to the system prompt
            let instruction_signature = format!(
                "{}{}({}): void {{}}",
                Self::FUNC_PREFIX,
                def.name,
                def.param_names
                    .iter()
                    .zip(arg_types.iter())
                    .map(|(name, type_)| format!("{}: {}", name, type_))
                    .collect::<Vec<_>>()
                    .join(", ")
            );

            instruction_definitions_str.push_str(&instruction_signature);
            instruction_definitions_str.push('\n');
        }
        instruction_definitions_str.push_str("```\n");

        // Extra data has the instruction definitions.
        let extra_data = json_map! {
            "instruction_definitions" => instruction_definitions_str,
        };

        println!("System prompt for instructor:\n{}", Self::SYSTEM_PROMPT);
        println!(
            "Instruction definitions for instructor:\n{}",
            instruction_definitions_str
        );

        let chat = Chat::new(
            model,
            Self::SYSTEM_PROMPT,
            &example_chat_history,
            &InferParams::new_logical(),
            Some(extra_data),
        );
        Self {
            chat,
            instruction_definitions,
        }
    }

    /// Parses the provided instruction text and returns the relevant information as a `ParsedInstruction`.
    pub fn parse_instruction<'a>(
        &'a mut self,
        instruction_text: impl AsRef<str>,
    ) -> Option<ParsedInstruction<'a>> {
        // Format the instruction text and push it to the chat
        let instruction_text = format!(
            "**Instruction Text:**\n{}",
            instruction_text.as_ref().trim()
        );
        self.chat
            .push_message(ChatMessage::new(ChatRole::User, instruction_text));

        // Keep trying until we successfully parse an instruction from the model's response
        let mut attempts = 0;
        let (instruction_def, args) = loop {
            // Infer a response from the model
            // We begin with the prefix so that the model won't generate it
            let begin_response = format!("**Function Call:**\n{}", Self::FUNC_PREFIX);
            if let Some((_func_name, (instruction_def, args))) = self.chat.infer_message_ext(
                &ChatRole::Assistant,
                Some(&begin_response),
                &["("],
                |func_name: &str, infer_iter: &mut InferIter, end_sequence: Option<&str>| {
                    // If the end sequence is not "(" then we return None since the model did not follow the expected format
                    if end_sequence != Some("(") {
                        return None;
                    }

                    // Match func_name to an instruction definition by name
                    let func_name = func_name.trim();
                    let instruction_def = self
                        .instruction_definitions
                        .iter()
                        .find(|def| def.name == func_name)?;

                    // Now we want to infer the arguments one by one, using the parameter names from the instruction definition as part of the prompt
                    let mut args = JsonMap::with_capacity(instruction_def.param_names.len());
                    for (i, param_name) in instruction_def.param_names.iter().enumerate() {
                        // Get the parameter type from the example arguments in the instruction definition
                        let example_arg = &instruction_def.example_args[i];
                        let param_type = if example_arg.is_string() {
                            "string"
                        } else if example_arg.is_number() {
                            "number"
                        } else if example_arg.is_boolean() {
                            "boolean"
                        } else if example_arg.is_array() {
                            "array"
                        } else {
                            "object"
                        };

                        // Push the parameter name and a : onto the context
                        infer_iter.push_str(param_name);
                        infer_iter.push_str(": ");

                        // Infer the argument value until we get a comma or a closing parenthesis.
                        // If this is a string then complete to a " instead
                        let arg_response = if param_type == "string" {
                            // First push a " to the context so that the model will generate a closing " at the end of the string argument
                            infer_iter.push_str("\"");
                            infer_iter.complete(&["\""])
                        } else {
                            infer_iter.complete(&[",", ")"])
                        };

                        // If the response ended with a closing parenthesis instead of a comma and we still have arguments left to infer, return None
                        if arg_response.end_sequence() == Some(")")
                            && i != instruction_def.param_names.len() - 1
                        {
                            return None;
                        }

                        // Store the argument value trimmed and converted to JsonValue of type matching the param definition
                        let arg_value = arg_response.trim().to_string();
                        let arg_value = match param_type {
                            "string" => JsonValue::String(arg_value.to_string()),
                            "number" => JsonValue::Number(arg_value.parse().expect("Failed to parse number argument")),
                            "boolean" => JsonValue::Bool(arg_value.parse().expect("Failed to parse boolean argument")),
                            "array" => unimplemented!("Array argument parsing not implemented (yet)"),
                            "object" => unimplemented!("Object argument parsing not implemented (yet)"),
                            _ => JsonValue::String(arg_value),
                        };
                        args.insert(param_name.clone(), arg_value);
                    }

                    Some((instruction_def, args))
                },
            ) {
                 break (instruction_def, args);
            }

            // If we got here then we failed to parse an instruction
            // Increment attempts and if we've reached the max attempts then we return None
            attempts += 1;
            if attempts >= Self::MAX_PARSE_ATTEMPTS {
                return None;
            }
        };

        // If we got here then we successfully parsed the instruction, so we return the parsed instruction
        Some(ParsedInstruction {
            name: &instruction_def.name,
            args,
        })
    }
}
